### ISSUE TITLE
weex debug src/index.vue error

### ISSUE THREAD

**Issue by iusn** [tw93/weex-ui-with-toolkit#2]
When run `weex debug src/index.vue`
Error:
[main.js:189:19427] SyntaxError: Unexpected identifier 'UrlParser'. import call expects exactly one argument.
Function@[native code]
Function@[native code]
m@main.js:4:19427
a@main.js:4:16690
main.js:7:8740
jsLog: Error: receiveTasks: instance 1 not found! 
----------------------------------------------------
`weex --version`
weexpack : v0.4.7-beta.26
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.2-beta.9
 - weex-previewer : v1.3.13-beta.13
 - toolkit-repair : v0.0.5

**Comment by guoshimeihua** [comment]
@iusn 你的问题有解决吗？我也遇到了这个问题了，报instance not found.

**Comment by tw93** [comment]
后续以这个项目为主哦 
https://github.com/tw93/weex-ui-demo
可以看readme
